#!/usr/bin/env python3
# Harrison Evans
# 9/8/21
# Challenge 7

# Import libraries

import os

# Declaration of variables
text1 = input("please enter the desired directory path: ")
  

### Read user input here into a variable



def taco():

    for (root, dirs, files) in os.walk(top=text1, topdown=True):
        ### Add a print command here to print ==root==
        print(root, "parent")
        ### Add a print command here to print ==dirs==
        dirs[:] = [x for x in dirs if not x.startswith('.')]
        print(dirs, "subdirectories")
        ### Add a print command here to print ==files==
        files[:] = [x for x in files if not x.startswith('.')]
        print(files, "Files")
# Main
taco()
### Pass the variable into the function here

# End

# im falling asllep here, im sure i may have missed somthing, thanks for the sharp eye on my last one, ill be sure to fix that.
