#!/usr/bin/env python3
#Harrison Evnas
#challenge 10
#9/13/21
# if-else statements
#main
a = "1"
b = "24"
if b == a:
    print("b is equals a")
else:
    print("b is not equal a")

if b > a:
    print("b is greater than a")
elif b < a:
    print("b is less than a ")
else:
    print("math is hard")

a = "8"
c = "10"
if a == c:
    print("a is equal to c")
else:
    print("a is not quaal to c")

if a > c:
    print("a is greater than c")
elif a < c:
    print("a is less then c")
else:
    print("math is hard")
#end
