#!/usr/bin/env python

#Harrison Evans
#November 8, 2021
# log errors
#harrison Evans

#resorces 
# https://stackoverflow.com/questions/5191830/how-do-i-log-a-python-error-with-debug-information
# not alot from ^ but alot of little things that helped me alone the way.
#https://www.kite.com/python/docs/os.environ
#https://www.toptal.com/python/in-depth-python-logging



#Import Library
import logging
import logging.handlers
import os

#Declaration of variable

log = logging.getLogger(__name__)
#Main

def do_something():
    log.debug("Doing something!")
handler = logging.handlers.WatchedFileHandler(
    os.environ.get("LOGFILE", "/home/harrison/log lab 26/log.log")) 
formatter = logging.Formatter(logging.BASIC_FORMAT)
handler.setFormatter(formatter)
root = logging.getLogger()
root.setLevel(os.environ.get("LOGLEVEL", "INFO"))
root.addHandler(handler)

try:
    exit(main())
except Exception:
    logging.exception("Exception in main()")
    exit(1)
