#!/usr/bin/env python3
#harrison Evnas
#challenge 6
#9/8/21
#



#main


x = "Aswsome!"
print("Python is " + x)
import os
os.system("sudo bash lshw.sh")
print("Next we will put your info about a domain into a file for refernce.")
import time ; time.sleep(4)
os.system("sudo bash infotofile.sh")
import time ; time.sleep(4)
print("Now to show the info in nano, go exit and continue, control+X")
import socket
h_name = socket.gethostname()
IP_addres = socket.gethostbyname(h_name)
print("Host Name is:" + h_name)
print("Computer IP Address is:" + IP_addres)
print("Challenge 6 Completed!")
#end
